//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.27 at 05:33:48 PM EST 
//


package com.bglp.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bglp.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bglp.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link Patient.Acceleration }
     * 
     */
    public Patient.Acceleration createPatientAcceleration() {
        return new Patient.Acceleration();
    }

    /**
     * Create an instance of {@link Patient.BasisSleep }
     * 
     */
    public Patient.BasisSleep createPatientBasisSleep() {
        return new Patient.BasisSleep();
    }

    /**
     * Create an instance of {@link Patient.BasisSkinTemperature }
     * 
     */
    public Patient.BasisSkinTemperature createPatientBasisSkinTemperature() {
        return new Patient.BasisSkinTemperature();
    }

    /**
     * Create an instance of {@link Patient.BasisGsr }
     * 
     */
    public Patient.BasisGsr createPatientBasisGsr() {
        return new Patient.BasisGsr();
    }

    /**
     * Create an instance of {@link Patient.Exercise }
     * 
     */
    public Patient.Exercise createPatientExercise() {
        return new Patient.Exercise();
    }

    /**
     * Create an instance of {@link Patient.HypoEvent }
     * 
     */
    public Patient.HypoEvent createPatientHypoEvent() {
        return new Patient.HypoEvent();
    }

    /**
     * Create an instance of {@link Patient.HypoEvent.Event }
     * 
     */
    public Patient.HypoEvent.Event createPatientHypoEventEvent() {
        return new Patient.HypoEvent.Event();
    }

    /**
     * Create an instance of {@link Patient.Stressors }
     * 
     */
    public Patient.Stressors createPatientStressors() {
        return new Patient.Stressors();
    }

    /**
     * Create an instance of {@link Patient.Work }
     * 
     */
    public Patient.Work createPatientWork() {
        return new Patient.Work();
    }

    /**
     * Create an instance of {@link Patient.Sleep }
     * 
     */
    public Patient.Sleep createPatientSleep() {
        return new Patient.Sleep();
    }

    /**
     * Create an instance of {@link Patient.Meal }
     * 
     */
    public Patient.Meal createPatientMeal() {
        return new Patient.Meal();
    }

    /**
     * Create an instance of {@link Patient.Bolus }
     * 
     */
    public Patient.Bolus createPatientBolus() {
        return new Patient.Bolus();
    }

    /**
     * Create an instance of {@link Patient.TempBasal }
     * 
     */
    public Patient.TempBasal createPatientTempBasal() {
        return new Patient.TempBasal();
    }

    /**
     * Create an instance of {@link Patient.Basal }
     * 
     */
    public Patient.Basal createPatientBasal() {
        return new Patient.Basal();
    }

    /**
     * Create an instance of {@link Patient.FingerStick }
     * 
     */
    public Patient.FingerStick createPatientFingerStick() {
        return new Patient.FingerStick();
    }

    /**
     * Create an instance of {@link Patient.GlucoseLevel }
     * 
     */
    public Patient.GlucoseLevel createPatientGlucoseLevel() {
        return new Patient.GlucoseLevel();
    }

    /**
     * Create an instance of {@link Patient.Acceleration.Event }
     * 
     */
    public Patient.Acceleration.Event createPatientAccelerationEvent() {
        return new Patient.Acceleration.Event();
    }

    /**
     * Create an instance of {@link Patient.BasisSleep.Event }
     * 
     */
    public Patient.BasisSleep.Event createPatientBasisSleepEvent() {
        return new Patient.BasisSleep.Event();
    }

    /**
     * Create an instance of {@link Patient.BasisSkinTemperature.Event }
     * 
     */
    public Patient.BasisSkinTemperature.Event createPatientBasisSkinTemperatureEvent() {
        return new Patient.BasisSkinTemperature.Event();
    }

    /**
     * Create an instance of {@link Patient.BasisGsr.Event }
     * 
     */
    public Patient.BasisGsr.Event createPatientBasisGsrEvent() {
        return new Patient.BasisGsr.Event();
    }

    /**
     * Create an instance of {@link Patient.Exercise.Event }
     * 
     */
    public Patient.Exercise.Event createPatientExerciseEvent() {
        return new Patient.Exercise.Event();
    }

    /**
     * Create an instance of {@link Patient.HypoEvent.Event.Symptom }
     * 
     */
    public Patient.HypoEvent.Event.Symptom createPatientHypoEventEventSymptom() {
        return new Patient.HypoEvent.Event.Symptom();
    }

    /**
     * Create an instance of {@link Patient.Stressors.Event }
     * 
     */
    public Patient.Stressors.Event createPatientStressorsEvent() {
        return new Patient.Stressors.Event();
    }

    /**
     * Create an instance of {@link Patient.Work.Event }
     * 
     */
    public Patient.Work.Event createPatientWorkEvent() {
        return new Patient.Work.Event();
    }

    /**
     * Create an instance of {@link Patient.Sleep.Event }
     * 
     */
    public Patient.Sleep.Event createPatientSleepEvent() {
        return new Patient.Sleep.Event();
    }

    /**
     * Create an instance of {@link Patient.Meal.Event }
     * 
     */
    public Patient.Meal.Event createPatientMealEvent() {
        return new Patient.Meal.Event();
    }

    /**
     * Create an instance of {@link Patient.Bolus.Event }
     * 
     */
    public Patient.Bolus.Event createPatientBolusEvent() {
        return new Patient.Bolus.Event();
    }

    /**
     * Create an instance of {@link Patient.TempBasal.Event }
     * 
     */
    public Patient.TempBasal.Event createPatientTempBasalEvent() {
        return new Patient.TempBasal.Event();
    }

    /**
     * Create an instance of {@link Patient.Basal.Event }
     * 
     */
    public Patient.Basal.Event createPatientBasalEvent() {
        return new Patient.Basal.Event();
    }

    /**
     * Create an instance of {@link Patient.FingerStick.Event }
     * 
     */
    public Patient.FingerStick.Event createPatientFingerStickEvent() {
        return new Patient.FingerStick.Event();
    }

    /**
     * Create an instance of {@link Patient.GlucoseLevel.Event }
     * 
     */
    public Patient.GlucoseLevel.Event createPatientGlucoseLevelEvent() {
        return new Patient.GlucoseLevel.Event();
    }

}
